name: Deploy https://cdn.d2.pub

on:
  push:
    branches:
      - master

env:
  SITE: https://cdn.d2.pub/
  QINIU_BUCKET: d2-cdn
  DIST_FOLDER: /dist
  PATH_SUFFIX: /preview

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Download qshell
      run: |
        wget http://devtools.qiniu.com/qshell-linux-x86-v2.4.0.zip
        unzip qshell-linux-x86-v2.4.0.zip
        mv qshell-linux-x86-v2.4.0 qshell
    - name: Install packages
      run: npm i
    - name: Build
      run: npm run build:preview
    - name: CDN login
      run: ./qshell account ${{ secrets.AK }} ${{ secrets.SK }} GITHUB_ACTION
    - name: CDN upload
      run: |
        REPO=${GITHUB_REPOSITORY//*\//}
        echo $SITE > cdnrefresh.txt
        ./qshell qupload2 \
        --src-dir=$GITHUB_WORKSPACE$DIST_FOLDER \
        --bucket=$QINIU_BUCKET \
        --key-prefix=$REPO$PATH_SUFFIX/ \
        --overwrite=true \
        --check-exists=true \
        --check-hash=true \
        --check-size=true \
        --rescan-local=true \
        --thread-count=32
    - name: CDN refresh
      run: ./qshell cdnrefresh --dirs -i ./cdnrefresh.txt